// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ConsumerConnectionConfig is an autogenerated mock type for the ConsumerConnectionConfig type
type ConsumerConnectionConfig struct {
	mock.Mock
}

// GetConnectionTimeout provides a mock function with given fields:
func (_m *ConsumerConnectionConfig) GetConnectionTimeout() time.Duration {
	ret := _m.Called()

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// GetTokenRequestHeaderName provides a mock function with given fields:
func (_m *ConsumerConnectionConfig) GetTokenRequestHeaderName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUserAgent provides a mock function with given fields:
func (_m *ConsumerConnectionConfig) GetUserAgent() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
