// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// DLQConfig is an autogenerated mock type for the DLQConfig type
type DLQConfig struct {
	mock.Mock
}

// GetDLQSummaryUpdateInterval provides a mock function with no fields
func (_m *DLQConfig) GetDLQSummaryUpdateInterval() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDLQSummaryUpdateInterval")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// NewDLQConfig creates a new instance of DLQConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDLQConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *DLQConfig {
	mock := &DLQConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
