// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// HTTPConfig is an autogenerated mock type for the HTTPConfig type
type HTTPConfig struct {
	mock.Mock
}

// GetHTTPListeningAddr provides a mock function with given fields:
func (_m *HTTPConfig) GetHTTPListeningAddr() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHTTPListeningAddr")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetHTTPReadTimeout provides a mock function with given fields:
func (_m *HTTPConfig) GetHTTPReadTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHTTPReadTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// GetHTTPWriteTimeout provides a mock function with given fields:
func (_m *HTTPConfig) GetHTTPWriteTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHTTPWriteTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// NewHTTPConfig creates a new instance of HTTPConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPConfig {
	mock := &HTTPConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
