// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// HTTPConfig is an autogenerated mock type for the HTTPConfig type
type HTTPConfig struct {
	mock.Mock
}

// GetHTTPListeningAddr provides a mock function with given fields:
func (_m *HTTPConfig) GetHTTPListeningAddr() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetHTTPReadTimeout provides a mock function with given fields:
func (_m *HTTPConfig) GetHTTPReadTimeout() time.Duration {
	ret := _m.Called()

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// GetHTTPWriteTimeout provides a mock function with given fields:
func (_m *HTTPConfig) GetHTTPWriteTimeout() time.Duration {
	ret := _m.Called()

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}
