// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// SchedulerConfig is an autogenerated mock type for the SchedulerConfig type
type SchedulerConfig struct {
	mock.Mock
}

// GetMinScheduleDelay provides a mock function with no fields
func (_m *SchedulerConfig) GetMinScheduleDelay() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMinScheduleDelay")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// GetSchedulerBatchSize provides a mock function with no fields
func (_m *SchedulerConfig) GetSchedulerBatchSize() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSchedulerBatchSize")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetSchedulerInterval provides a mock function with no fields
func (_m *SchedulerConfig) GetSchedulerInterval() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSchedulerInterval")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// NewSchedulerConfig creates a new instance of SchedulerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchedulerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchedulerConfig {
	mock := &SchedulerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
