// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	config "github.com/imyousuf/webhook-broker/config"
	mock "github.com/stretchr/testify/mock"
)

// SeedDataConfig is an autogenerated mock type for the SeedDataConfig type
type SeedDataConfig struct {
	mock.Mock
}

// GetSeedData provides a mock function with given fields:
func (_m *SeedDataConfig) GetSeedData() config.SeedData {
	ret := _m.Called()

	var r0 config.SeedData
	if rf, ok := ret.Get(0).(func() config.SeedData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.SeedData)
	}

	return r0
}
