// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	config "github.com/newscred/webhook-broker/config"
	mock "github.com/stretchr/testify/mock"
)

// SeedDataConfig is an autogenerated mock type for the SeedDataConfig type
type SeedDataConfig struct {
	mock.Mock
}

// GetSeedData provides a mock function with no fields
func (_m *SeedDataConfig) GetSeedData() config.SeedData {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSeedData")
	}

	var r0 config.SeedData
	if rf, ok := ret.Get(0).(func() config.SeedData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.SeedData)
	}

	return r0
}

// NewSeedDataConfig creates a new instance of SeedDataConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeedDataConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *SeedDataConfig {
	mock := &SeedDataConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
