{{- if and .Values.gatewayApi.enabled (eq .Values.provider "gcp") -}}
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "webhook-broker-chart.fullname" . }}
  labels:
    {{- include "webhook-broker-chart.labels" . | nindent 4 }}
spec:
  default:
    logging:
      enabled: {{ .Values.gatewayApi.loggingEnabled }}
    connectionDraining:
      drainingTimeoutSec: {{ .Values.gatewayApi.connectionDrainingTimeoutSec }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "webhook-broker-chart.fullname" . }}
{{- end }}
