---
{{- if .Values.broker.dbPruning.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "webhook-broker-chart.fullname" . }}
  labels:
    type: local
    pv-name: {{ include "webhook-broker-chart.fullname" . }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.broker.dbPruning.pvStorage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/data/{{ include "webhook-broker-chart.fullname" . }}"
  persistentVolumeReclaimPolicy: {{ .Values.broker.dbPruning.pvReclaimPolicy }}
{{- end }}

---
{{- if .Values.broker.dbPruning.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "webhook-broker-chart.fullname" . }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.broker.dbPruning.pvStorage }}
  selector:
    matchLabels:
      pv-name: {{ include "webhook-broker-chart.fullname" . }}
{{- end }}
