{{- if and .Values.useEksSecurityGroupForPods (eq .Values.provider "aws") -}}
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: {{ include "webhook-broker-chart.name" . }}
  labels:
    {{- include "webhook-broker-chart.labels" . | nindent 4 }}
  {{- with .Values.securityGroupPolicyAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "webhook-broker-chart.name" . }}
  securityGroups:
    groupIds: {{ .Values.securityGroups }}
{{- end -}}
