// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	data "github.com/newscred/webhook-broker/storage/data"

	mock "github.com/stretchr/testify/mock"
)

// MessageDispatcher is an autogenerated mock type for the MessageDispatcher type
type MessageDispatcher struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: message
func (_m *MessageDispatcher) Dispatch(message *data.Message) {
	_m.Called(message)
}

// Stop provides a mock function with no fields
func (_m *MessageDispatcher) Stop() {
	_m.Called()
}

// NewMessageDispatcher creates a new instance of MessageDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageDispatcher {
	mock := &MessageDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
