// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	data "github.com/imyousuf/webhook-broker/storage/data"

	mock "github.com/stretchr/testify/mock"
)

// MessageDispatcher is an autogenerated mock type for the MessageDispatcher type
type MessageDispatcher struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: message
func (_m *MessageDispatcher) Dispatch(message *data.Message) {
	_m.Called(message)
}

// Stop provides a mock function with given fields:
func (_m *MessageDispatcher) Stop() {
	_m.Called()
}
