// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/imyousuf/webhook-broker/config"
	"github.com/imyousuf/webhook-broker/controllers"
	"github.com/imyousuf/webhook-broker/dispatcher"
	"github.com/imyousuf/webhook-broker/storage"
)

// Injectors from wire.go:

func GetAppVersion() config.AppVersion {
	appVersion := config.GetVersion()
	return appVersion
}

func GetHTTPServer(cliConfig *config.CLIConfig) (*HTTPServiceContainer, error) {
	configConfig, err := config.GetConfigurationFromCLIConfig(cliConfig)
	if err != nil {
		return nil, err
	}
	serverLifecycleListenerImpl := NewServerListener()
	migrationConfig := GetMigrationConfig(cliConfig)
	dataAccessor, err := storage.GetNewDataAccessor(configConfig, migrationConfig, configConfig)
	if err != nil {
		return nil, err
	}
	appRepository := newAppRepository(dataAccessor)
	statusController := controllers.NewStatusController(appRepository)
	producerRepository := newProducerRepository(dataAccessor)
	producerController := controllers.NewProducerController(producerRepository)
	producersController := controllers.NewProducersController(producerRepository, producerController)
	channelRepository := newChannelRepository(dataAccessor)
	consumerRepository := newConsumerRepository(dataAccessor)
	messageRepository := newMessageRepository(dataAccessor)
	deliveryJobRepository := newDeliveryJobRepository(dataAccessor)
	messageController := controllers.NewMessageController(messageRepository, deliveryJobRepository)
	dlqController := controllers.NewDLQController(messageController, deliveryJobRepository, consumerRepository)
	consumerController := controllers.NewConsumerController(channelRepository, consumerRepository, dlqController)
	consumersController := controllers.NewConsumersController(consumerController, consumerRepository)
	messagesController := controllers.NewMessagesController(messageController, messageRepository)
	lockRepository := newLockRepository(dataAccessor)
	configuration := &dispatcher.Configuration{
		DeliveryJobRepo:          deliveryJobRepository,
		ConsumerRepo:             consumerRepository,
		LockRepo:                 lockRepository,
		BrokerConfig:             configConfig,
		ConsumerConnectionConfig: configConfig,
		MsgRepo:                  messageRepository,
	}
	messageDispatcher := dispatcher.NewMessageDispatcher(configuration)
	broadcastController := controllers.NewBroadcastController(channelRepository, messageRepository, producerRepository, messageDispatcher)
	channelController := controllers.NewChannelController(consumersController, messagesController, broadcastController, channelRepository)
	controllersControllers := &controllers.Controllers{
		StatusController:    statusController,
		ProducersController: producersController,
		ProducerController:  producerController,
		ChannelController:   channelController,
		ConsumerController:  consumerController,
		ConsumersController: consumersController,
		BroadcastController: broadcastController,
		MessageController:   messageController,
		MessagesController:  messagesController,
		DLQController:       dlqController,
	}
	router := controllers.NewRouter(controllersControllers)
	server := controllers.ConfigureAPI(configConfig, serverLifecycleListenerImpl, router)
	httpServiceContainer := &HTTPServiceContainer{
		Configuration: configConfig,
		Server:        server,
		DataAccessor:  dataAccessor,
		Listener:      serverLifecycleListenerImpl,
		Dispatcher:    messageDispatcher,
	}
	return httpServiceContainer, nil
}
