// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/imyousuf/webhook-broker/config"
	"github.com/imyousuf/webhook-broker/controllers"
	"github.com/imyousuf/webhook-broker/storage"
)

// Injectors from wire.go:

func GetAppVersion() config.AppVersion {
	appVersion := config.GetVersion()
	return appVersion
}

func GetHTTPServer(cliConfig *config.CLIConfig) (*HTTPServiceContainer, error) {
	configConfig, err := config.GetConfigurationFromCLIConfig(cliConfig)
	if err != nil {
		return nil, err
	}
	serverLifecycleListenerImpl := NewServerListener()
	migrationConfig := GetMigrationConfig(cliConfig)
	db, err := storage.GetConnectionPool(configConfig, migrationConfig, configConfig)
	if err != nil {
		return nil, err
	}
	appRepository, err := storage.NewAppRepository(db)
	if err != nil {
		return nil, err
	}
	statusController := controllers.NewStatusController(appRepository)
	router := controllers.NewRouter(statusController)
	server := controllers.ConfigureAPI(configConfig, serverLifecycleListenerImpl, router)
	dataAccessor, err := storage.NewDataAccessor(db, appRepository)
	if err != nil {
		return nil, err
	}
	httpServiceContainer := NewHTTPServiceContainer(configConfig, serverLifecycleListenerImpl, server, dataAccessor)
	return httpServiceContainer, nil
}
