// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	config "github.com/newscred/webhook-broker/config"
	data "github.com/newscred/webhook-broker/storage/data"

	mock "github.com/stretchr/testify/mock"
)

// AppRepository is an autogenerated mock type for the AppRepository type
type AppRepository struct {
	mock.Mock
}

// CompleteAppInit provides a mock function with no fields
func (_m *AppRepository) CompleteAppInit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CompleteAppInit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetApp provides a mock function with no fields
func (_m *AppRepository) GetApp() (*data.App, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetApp")
	}

	var r0 *data.App
	var r1 error
	if rf, ok := ret.Get(0).(func() (*data.App, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *data.App); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.App)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartAppInit provides a mock function with given fields: _a0
func (_m *AppRepository) StartAppInit(_a0 *config.SeedData) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for StartAppInit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.SeedData) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAppRepository creates a new instance of AppRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppRepository {
	mock := &AppRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
