// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	config "github.com/newscred/webhook-broker/config"
	data "github.com/newscred/webhook-broker/storage/data"

	mock "github.com/stretchr/testify/mock"
)

// AppRepository is an autogenerated mock type for the AppRepository type
type AppRepository struct {
	mock.Mock
}

// CompleteAppInit provides a mock function with given fields:
func (_m *AppRepository) CompleteAppInit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetApp provides a mock function with given fields:
func (_m *AppRepository) GetApp() (*data.App, error) {
	ret := _m.Called()

	var r0 *data.App
	if rf, ok := ret.Get(0).(func() *data.App); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.App)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartAppInit provides a mock function with given fields: _a0
func (_m *AppRepository) StartAppInit(_a0 *config.SeedData) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.SeedData) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
