// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	storage "github.com/imyousuf/webhook-broker/storage"
	mock "github.com/stretchr/testify/mock"
)

// DataAccessor is an autogenerated mock type for the DataAccessor type
type DataAccessor struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *DataAccessor) Close() {
	_m.Called()
}

// GetAppRepository provides a mock function with given fields:
func (_m *DataAccessor) GetAppRepository() storage.AppRepository {
	ret := _m.Called()

	var r0 storage.AppRepository
	if rf, ok := ret.Get(0).(func() storage.AppRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.AppRepository)
		}
	}

	return r0
}

// GetChannelRepository provides a mock function with given fields:
func (_m *DataAccessor) GetChannelRepository() storage.ChannelRepository {
	ret := _m.Called()

	var r0 storage.ChannelRepository
	if rf, ok := ret.Get(0).(func() storage.ChannelRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.ChannelRepository)
		}
	}

	return r0
}

// GetConsumerRepository provides a mock function with given fields:
func (_m *DataAccessor) GetConsumerRepository() storage.ConsumerRepository {
	ret := _m.Called()

	var r0 storage.ConsumerRepository
	if rf, ok := ret.Get(0).(func() storage.ConsumerRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.ConsumerRepository)
		}
	}

	return r0
}

// GetMessageRepository provides a mock function with given fields:
func (_m *DataAccessor) GetMessageRepository() storage.MessageRepository {
	ret := _m.Called()

	var r0 storage.MessageRepository
	if rf, ok := ret.Get(0).(func() storage.MessageRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.MessageRepository)
		}
	}

	return r0
}

// GetProducerRepository provides a mock function with given fields:
func (_m *DataAccessor) GetProducerRepository() storage.ProducerRepository {
	ret := _m.Called()

	var r0 storage.ProducerRepository
	if rf, ok := ret.Get(0).(func() storage.ProducerRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.ProducerRepository)
		}
	}

	return r0
}
