// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	data "github.com/newscred/webhook-broker/storage/data"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	time "time"
)

// DLQSummaryRepository is an autogenerated mock type for the DLQSummaryRepository type
type DLQSummaryRepository struct {
	mock.Mock
}

// BootstrapCounts provides a mock function with given fields: db
func (_m *DLQSummaryRepository) BootstrapCounts(db *sql.DB) error {
	ret := _m.Called(db)

	if len(ret) == 0 {
		panic("no return value specified for BootstrapCounts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.DB) error); ok {
		r0 = rf(db)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrementCount provides a mock function with given fields: consumerID, count
func (_m *DLQSummaryRepository) DecrementCount(consumerID string, count int64) error {
	ret := _m.Called(consumerID, count)

	if len(ret) == 0 {
		panic("no return value specified for DecrementCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(consumerID, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *DLQSummaryRepository) GetAll() ([]*data.DLQSummary, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*data.DLQSummary
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*data.DLQSummary, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*data.DLQSummary); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.DLQSummary)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastCheckedAt provides a mock function with no fields
func (_m *DLQSummaryRepository) GetLastCheckedAt() (time.Time, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastCheckedAt")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func() (time.Time, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertCounts provides a mock function with given fields: summaries
func (_m *DLQSummaryRepository) UpsertCounts(summaries []*data.DLQSummary) error {
	ret := _m.Called(summaries)

	if len(ret) == 0 {
		panic("no return value specified for UpsertCounts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*data.DLQSummary) error); ok {
		r0 = rf(summaries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDLQSummaryRepository creates a new instance of DLQSummaryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDLQSummaryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DLQSummaryRepository {
	mock := &DLQSummaryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
