// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Lockable is an autogenerated mock type for the Lockable type
type Lockable struct {
	mock.Mock
}

// GetLockID provides a mock function with given fields:
func (_m *Lockable) GetLockID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
