// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	data "github.com/newscred/webhook-broker/storage/data"
	mock "github.com/stretchr/testify/mock"
)

// Paginateable is an autogenerated mock type for the Paginateable type
type Paginateable struct {
	mock.Mock
}

// GetCursor provides a mock function with given fields:
func (_m *Paginateable) GetCursor() (*data.Cursor, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCursor")
	}

	var r0 *data.Cursor
	var r1 error
	if rf, ok := ret.Get(0).(func() (*data.Cursor, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *data.Cursor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Cursor)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaginateable creates a new instance of Paginateable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaginateable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Paginateable {
	mock := &Paginateable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
