// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	data "github.com/newscred/webhook-broker/storage/data"
	mock "github.com/stretchr/testify/mock"
)

// Paginateable is an autogenerated mock type for the Paginateable type
type Paginateable struct {
	mock.Mock
}

// GetCursor provides a mock function with given fields:
func (_m *Paginateable) GetCursor() (*data.Cursor, error) {
	ret := _m.Called()

	var r0 *data.Cursor
	if rf, ok := ret.Get(0).(func() *data.Cursor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Cursor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
