// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidateableModel is an autogenerated mock type for the ValidateableModel type
type ValidateableModel struct {
	mock.Mock
}

// IsInValidState provides a mock function with no fields
func (_m *ValidateableModel) IsInValidState() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInValidState")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// QuickFix provides a mock function with no fields
func (_m *ValidateableModel) QuickFix() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for QuickFix")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewValidateableModel creates a new instance of ValidateableModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidateableModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidateableModel {
	mock := &ValidateableModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
