name: Webhook Broker Container Build & Push

on:
  push:
    branches: [ main ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    -
      name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    -
      name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - 
      name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_PUBLIC_ECR_HELM_IAM_ROLE }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - 
      name: Docker Login to ECR
      uses: docker/login-action@v1
      with:
        registry: ${{ steps.login-ecr-public.outputs.registry }}

    -
      name: Build and Push
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ steps.login-ecr-public.outputs.registry }}/optimizely/webhook-broker:${{ github.sha }}
          ${{ steps.login-ecr-public.outputs.registry }}/optimizely/webhook-broker:latest
