name: Webhook Broker Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  integration-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-buildx-action@v2
    - name: Generate Pruner Dockerfile
      run: /usr/bin/bash ./build/scripts/prune-dockerfile-generator.sh
    - name: Run Integration Test
      run: make itest
